[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["firebase-admin"]

[dev]
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Add environment variables
[context.production.environment]
  VITE_NETLIFY_URL = "https://${NETLIFY_SITE_NAME}.netlify.app"

[context.deploy-preview.environment]
  VITE_NETLIFY_URL = "${DEPLOY_PRIME_URL}"

[context.branch-deploy.environment]
  VITE_NETLIFY_URL = "${DEPLOY_PRIME_URL}"